'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Terminal } from 'lucide-react';

const MCP_SERVERS = {
  discovery: {
    name: 'DISCOVERY',
    description: 'Search & discover markets across all platforms',
    url: 'https://quantish.live/mcp',
    tag: 'read-only',
  },
  polymarket: {
    name: 'POLYMARKET',
    description: 'Trade on the world\'s largest prediction market',
    url: 'https://quantish-sdk-production.up.railway.app/mcp',
    tag: 'polygon',
  },
  kalshi: {
    name: 'KALSHI',
    description: 'CFTC-regulated prediction markets on Solana',
    url: 'https://kalshi-mcp-production-7c2c.up.railway.app/mcp',
    tag: 'solana',
  },
  limitless: {
    name: 'LIMITLESS',
    description: 'Trade prediction markets on Base chain',
    url: 'https://limitless-mcp-server-production.up.railway.app/mcp',
    tag: 'base',
  },
};

interface ServerKey {
  apiKey: string;
  apiSecret?: string;
  address?: string;
}

// ASCII Art Logo - QUANTISH (Gemini CLI style, generated by Gemini 3.1 Pro)
const ASCII_LOGO = `
  ██████    ███    ███     ████     ███    ███  ██████████   ████     ██████    ███    ███
███    ███  ███    ███   ███  ███   ████   ███     ████     ████   ████        ███    ███
███    ███  ███    ███  ██████████  ███ ██ ███     ████     ████     ██████    ██████████
███   ████  ███    ███  ███    ███  ███  █████     ████     ████         ████  ███    ███
  ████████  ███    ███  ███    ███  ███   ████     ████     ████   ████  ████  ███    ███
        ██    ██████    ███    ███  ███    ███     ████     ████     ██████    ███    ███`;

export default function Home() {
  const [externalId, setExternalId] = useState('');
  const [isLoading, setIsLoading] = useState<Record<string, boolean>>({});
  const [keys, setKeys] = useState<Record<string, ServerKey>>({});
  const [copiedItem, setCopiedItem] = useState<string | null>(null);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const copyToClipboard = async (text: string, itemId: string) => {
    await navigator.clipboard.writeText(text);
    setCopiedItem(itemId);
    setTimeout(() => setCopiedItem(null), 2000);
  };

  const generateDiscoveryKey = async () => {
    setIsLoading(prev => ({ ...prev, discovery: true }));
    setErrors(prev => ({ ...prev, discovery: '' }));
    try {
      const response = await fetch('/api/generate-discovery-key', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: externalId.trim() })
      });
      const data = await response.json();
      if (data.success && data.key) {
        setKeys(prev => ({ ...prev, discovery: { apiKey: data.key } }));
      } else {
        setErrors(prev => ({ ...prev, discovery: data.error || 'Failed to generate key' }));
      }
    } catch {
      setErrors(prev => ({ ...prev, discovery: 'Network error. Try again.' }));
    } finally {
      setIsLoading(prev => ({ ...prev, discovery: false }));
    }
  };

  const generatePolymarketKey = async () => {
    setIsLoading(prev => ({ ...prev, polymarket: true }));
    setErrors(prev => ({ ...prev, polymarket: '' }));
    try {
      const response = await fetch(MCP_SERVERS.polymarket.url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jsonrpc: '2.0', id: 1,
          method: 'tools/call',
          params: { name: 'request_api_key', arguments: { externalId: externalId.trim() } }
        })
      });
      const data = await response.json();
      const result = data.result?.content?.[0]?.text ? JSON.parse(data.result.content[0].text) : null;
      if (result?.apiKey) {
        setKeys(prev => ({ ...prev, polymarket: { apiKey: result.apiKey, apiSecret: result.apiSecret, address: result.eoaAddress } }));
      } else {
        setErrors(prev => ({ ...prev, polymarket: result?.error || 'Failed to generate key' }));
      }
    } catch {
      setErrors(prev => ({ ...prev, polymarket: 'Network error. Try again.' }));
    } finally {
      setIsLoading(prev => ({ ...prev, polymarket: false }));
    }
  };

  const generateKalshiKey = async () => {
    setIsLoading(prev => ({ ...prev, kalshi: true }));
    setErrors(prev => ({ ...prev, kalshi: '' }));
    try {
      const response = await fetch(MCP_SERVERS.kalshi.url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          jsonrpc: '2.0', id: 1,
          method: 'tools/call',
          params: { name: 'kalshi_signup', arguments: { externalId: externalId.trim() } }
        })
      });
      const data = await response.json();
      const result = data.result?.content?.[0]?.text ? JSON.parse(data.result.content[0].text) : null;
      if (result?.apiKey) {
        setKeys(prev => ({ ...prev, kalshi: { apiKey: result.apiKey } }));
      } else {
        setErrors(prev => ({ ...prev, kalshi: result?.error || 'Failed to generate key' }));
      }
    } catch {
      setErrors(prev => ({ ...prev, kalshi: 'Network error. Try again.' }));
    } finally {
      setIsLoading(prev => ({ ...prev, kalshi: false }));
    }
  };

  const generateAllKeys = async () => {
    if (!externalId.trim()) return;
    await Promise.all([
      generateDiscoveryKey(),
      generatePolymarketKey(),
      generateKalshiKey(),
    ]);
  };

  return (
    <div className="landing-page">
      {/* ASCII Art Hero */}
      <section className="ascii-hero">
        <pre className="ascii-logo">{ASCII_LOGO}</pre>
        <div className="hero-badge">
          <span className="version-tag">v3.0</span>
          <span className="stats">50+ MCP tools • 39,000+ markets</span>
        </div>
        <p className="hero-tagline">Unified Prediction Market Infrastructure</p>
        <p className="hero-subtitle">
          Search markets, place trades, and manage wallets across
          Polymarket, Kalshi, and Limitless through MCP servers built for AI agents.
        </p>
        <div className="hero-actions">
          <Link href="/introduction" className="btn-primary">
            Get Started <ArrowRight className="w-4 h-4" />
          </Link>
          <Link href="/mcp" className="btn-ghost">
            View MCP Servers
          </Link>
        </div>
      </section>

      {/* Platform Logos */}
      <section className="platform-section">
        <p className="section-label">Supported Platforms</p>
        <div className="platform-grid">
          <div className="platform-item">
            <Image src="/polymarket-logo.png" alt="Polymarket" width={32} height={32} className="platform-img" />
            <span>Polymarket</span>
          </div>
          <div className="platform-item">
            <Image src="/kalshi-logo.jpg" alt="Kalshi" width={32} height={32} className="platform-img" />
            <span>Kalshi</span>
          </div>
          <div className="platform-item">
            <Image src="/limitless-logo.jpg" alt="Limitless" width={32} height={32} className="platform-img" />
            <span>Limitless</span>
          </div>
        </div>
      </section>

      {/* Key Generator */}
      <section className="generator-section">
        <h2>Get API Keys</h2>
        <p>Enter your email to generate keys for each MCP server.</p>
        <div className="generator-card">
          <input
            type="email"
            value={externalId}
            onChange={(e) => setExternalId(e.target.value)}
            placeholder="your@email.com"
            className="input-dark"
          />
          <button
            onClick={generateAllKeys}
            disabled={!externalId.trim() || Object.values(isLoading).some(Boolean)}
            className="btn-primary"
          >
            {Object.values(isLoading).some(Boolean) ? 'Generating...' : 'Generate All Keys'}
          </button>
        </div>

        {/* Generated Keys */}
        {Object.keys(keys).length > 0 && (
          <div className="keys-list">
            {Object.entries(keys).map(([server, key]) => (
              <div key={server} className="key-item">
                <div>
                  <span className="key-server">{server}</span>
                  <code className="key-value">{key.apiKey.slice(0, 20)}...</code>
                </div>
                <button onClick={() => copyToClipboard(key.apiKey, server)} className="btn-ghost btn-sm">
                  {copiedItem === server ? 'Copied!' : 'Copy'}
                </button>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* Features - Clean List Style */}
      <section className="features-list-section">
        <h2>Built for AI Agents</h2>

        <div className="feature-row">
          <div className="feature-content">
            <h3>Search 39,000+ Markets</h3>
            <p>Find markets across Polymarket, Kalshi, and Limitless with semantic search.</p>
            <code className="feature-example">search_markets "bitcoin above $100k by 2027"</code>
          </div>
        </div>

        <div className="feature-row">
          <div className="feature-content">
            <h3>Place Orders Instantly</h3>
            <p>Buy YES or NO shares on any market with gasless transactions.</p>
            <code className="feature-example">place_order "Trump tariff China" YES 100 @ 0.65</code>
          </div>
        </div>

        <div className="feature-row">
          <div className="feature-content">
            <h3>Track Whale Activity</h3>
            <p>See what the top traders are betting on, their PnL, and copy their moves.</p>
            <code className="feature-example">get_whale_activity "0x742d..." → $47K vol, +234% ROI</code>
          </div>
        </div>

        <div className="feature-row">
          <div className="feature-content">
            <h3>Find Arbitrage</h3>
            <p>Scan for spread opportunities where YES + NO &lt; $1 across all platforms.</p>
            <code className="feature-example">find_arbitrage → 2.3% profit on "Fed rate cut March"</code>
          </div>
        </div>
      </section>

      {/* Integration Options */}
      <section className="integrations-section">
        <h2>Two Ways to Integrate</h2>
        <div className="integrations-list">
          <Link href="/mcp" className="integration-row">
            <div className="integration-row-content">
              <span className="integration-tag tag-mcp">MCP</span>
              <h3>MCP Servers</h3>
              <p>Model Context Protocol for AI agents. Connect to Cursor, Claude Desktop, or any MCP client.</p>
            </div>
            <ArrowRight className="w-4 h-4 text-[var(--pn-text-muted)]" />
          </Link>

          <a href="https://github.com/joinQuantish" className="integration-row">
            <div className="integration-row-content">
              <span className="integration-tag tag-skill">Skills</span>
              <h3>Claude Code Skills</h3>
              <p>Drop-in skills for Claude Code CLI. One command to start trading.</p>
            </div>
            <ArrowRight className="w-4 h-4 text-[var(--pn-text-muted)]" />
          </a>
        </div>
      </section>

      {/* Terminal Example */}
      <section className="terminal-section">
        <h2><Terminal className="inline w-5 h-5 mr-2" />Quick Example</h2>
        <div className="terminal-window">
          <div className="terminal-header">
            <span className="terminal-dot red"></span>
            <span className="terminal-dot yellow"></span>
            <span className="terminal-dot green"></span>
            <span className="terminal-title">terminal</span>
          </div>
          <pre className="terminal-body">
{`# Search for markets
curl "https://quantish.live/mcp" \\
  -H "x-api-key: YOUR_KEY" \\
  -d '{"method":"tools/call","params":{"name":"search_markets","arguments":{"query":"bitcoin"}}}'

# Buy shares on Polymarket
curl "https://quantish-sdk-production.up.railway.app/mcp" \\
  -H "x-api-key: YOUR_KEY" \\
  -d '{"method":"tools/call","params":{"name":"place_order","arguments":{...}}}'`}
          </pre>
        </div>
      </section>

      {/* CTA */}
      <section className="cta-section">
        <h2>Ready to start?</h2>
        <p>Generate your API keys and start trading prediction markets.</p>
        <div className="cta-actions">
          <Link href="/introduction/quickstart" className="btn-primary">
            Quick Start <ArrowRight className="w-4 h-4" />
          </Link>
          <a href="https://github.com/joinQuantish" className="btn-ghost">
            View on GitHub
          </a>
        </div>
      </section>
    </div>
  );
}
